reportWebAddress: "https://report.trueog.net"
appealWebAddress: "https://appeal.trueog.net"

sqlType: mariadb # Options: mariadb or mysql
sqlHost: localhost
sqlUsername: $MARIADB_USER
sqlPassword: $MARIADB_PASSWORD
sqlDatabase: staffog
sqlPort: 3306
